### ISSUE TITLE
Linux Executable

### ISSUE THREAD

**Issue by dianshane** [Zenahr/lichess-desktop-app#2]
Hello, just a quick detail. On the Linux package you have forgotten to make the binary executable!
Its not a big deal but some users might not know how to do it and its a very easy fix!
(If you're developing on windows and need info please just email me I am a Linux user and Developer and very happy to help)

Have a nice day and lots of thanx for the app i love it!

Shane from Greece

**Comment by ZenaMel** [comment]
I'm not a Linux user. If you're able to provide a runnable Linux package I'm more than happy to link it on my page.

**Comment by ZenaMel** [comment]
Closing because: *stale*
